language: php

services:
  - mongodb
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" && $TRAVIS_PHP_VERSION != "7.0" ]]; then sh ./tests/travis.sh; fi
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction --no-progress

script:
  - vendor/bin/phpunit --verbose
