language: php

services:
  - mongodb
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" && $TRAVIS_PHP_VERSION != "7.0" ]]; then sh ./tests/travis.sh; fi
  - composer self-update

install:
  - composer require satooshi/php-coveralls:~0.6@stable --no-update
  - composer install --prefer-dist --no-interaction --no-progress

before_script:
  - vendor/bin/php-cs-fixer -v fix --diff --dry-run

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [[ $TRAVIS_PHP_VERSION != "5.6" && $TRAVIS_PULL_REQUEST == "false" ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi

notifications:
  email: false
